/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestTaskContract__factory } from "./TestTaskContract__factory";
export { USDT__factory } from "./USDT__factory";
